{{- if .Values.enabled}}
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ template "crunchy-postgres.fullname" . }}
  labels: {{ include "crunchy-postgres.labels" . | nindent 4 }}
spec:
  metadata:
    labels: {{ include "crunchy-postgres.labels" . | nindent 6 }}
  {{ if .Values.crunchyImage }}
  image: {{ .Values.crunchyImage }}
  {{ end }}
  imagePullPolicy: {{.Values.imagePullPolicy}}
  postgresVersion: {{ .Values.postgresVersion }}
  {{ if .Values.postGISVersion }}
  postGISVersion: {{ .Values.postGISVersion | quote }}
  {{ end }}
  postgresVersion: {{ .Values.postgresVersion }}
  {{- if and .Values.clone .Values.clone.enabled }} # enabled in disaster recovery scenario
  dataSource:
    pgbackrest:
      stanza: {{ .Values.instances.name }}
      configuration:
        - secret:
            name: {{ .Release.Name }}-s3-secret
      global:
        repo1-s3-uri-style: path # This is mandatory since the backups are path based.
        repo1-path: {{ .Values.clone.path }} # path to the backup where cluster will bootstrap from
      repo:
        name: repo1 # hardcoded since it is always backed up to object storage.
        s3:
          bucket: {{ .Values.pgBackRest.s3.bucket }}
          endpoint: {{ .Values.pgBackRest.s3.endpoint }}
          region: "ca-central-1"
  {{- end}}
  {{ if .Values.pgmonitor.enabled }}

  # Added to ensure openshift security context compatibility
  openshift: true
  {{- if .Values.databaseInitSQL }}
  databaseInitSQL:
    name: {{ required "A ConfigMap name is required for running bootstrap SQL." .Values.databaseInitSQL.name | quote }}
    key: {{ required "A key in a ConfigMap containing any bootstrap SQL is required." .Values.databaseInitSQL.key | quote }}
  {{- end }}
  monitoring:
    pgmonitor:
      # this stuff is for the "exporter" container in the "postgres-cluster-ha" set of pods
      exporter:
        {{ if .Values.pgmonitor.exporter.image}}
        image: {{ .Values.pgmonitor.exporter.image}}
        {{ end }}
        resources:
          requests:
            cpu: {{ .Values.pgmonitor.exporter.requests.cpu }}
            memory: {{ .Values.pgmonitor.exporter.requests.memory }}

  {{ end }}

  instances:
    - name: {{ .Values.instances.name }}
      {{- if .Values.instances.metadata }}
      metadata:
        {{- toYaml .Values.instances.metadata | nindent 8 }}
      {{- end }}
      replicas: {{ .Values.instances.replicas }}
      resources:
        requests:
          cpu: {{ .Values.instances.requests.cpu }}
          memory: {{ .Values.instances.requests.memory }}
      sidecars:
        replicaCertCopy:
          resources:
            requests:
              cpu: {{ .Values.instances.replicaCertCopy.requests.cpu }}
              memory: {{ .Values.instances.replicaCertCopy.requests.memory }}
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.instances.dataVolumeClaimSpec.storage }}
        storageClassName: {{ .Values.instances.dataVolumeClaimSpec.storageClassName }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster:
                      {{ template "crunchy-postgres.fullname" . }}
                    postgres-operator.crunchydata.com/instance-set: {{ .Values.instances.name }}-ha

  users:
    - name: {{ .Values.global.secrets.databaseUser }}
      databases:
        - {{ .Values.global.secrets.databaseName }}
      options: "CREATEROLE"
    - name: postgres
      databases:
        - postgres
    {{- if .Values.pgBackRest.enabled }}
  backups:
    pgbackrest:
      {{ if .Values.pgBackRest.image }}
      image: {{ .Values.pgBackRest.image }}
      {{ end }}
      configuration:
        - secret:
            name: {{ .Release.Name }}-s3-secret
      global:
        repo1-retention-full: {{ .Values.pgBackRest.s3.retention | quote }}
        repo1-retention-full-type: {{ .Values.pgBackRest.retentionFullType }}
        repo1-path: '{{ .Values.pgBackRest.backupPath }}/{{ .Values.pgBackRest.clusterCounter}}'
        repo1-s3-uri-style: path
         
        repo2-retention-full: {{ .Values.pgBackRest.pvc.retention | quote }}
        repo2-retention-full-type: {{ .Values.pgBackRest.pvc.retentionFullType }}
      repos:
        - name: repo1
          schedules:
            full: {{ .Values.pgBackRest.s3.fullBackupSchedule }}
            incremental: {{ .Values.pgBackRest.s3.incrementalBackupSchedule }}
          s3:
            bucket: {{ .Values.pgBackRest.s3.bucket }}
            endpoint: {{ .Values.pgBackRest.s3.endpoint }}
            region: "ca-central-1"
        - name: repo2
          schedules:
            full: {{ .Values.pgBackRest.pvc.fullBackupSchedule }}
            incremental: {{ .Values.pgBackRest.pvc.incrementalBackupSchedule }}
          volume:
            volumeClaimSpec:
              accessModes:
                - {{ .Values.pgBackRest.pvc.volume.accessModes }}
              resources:
                requests:
                  storage: {{ .Values.pgBackRest.pvc.volume.storage }}
              storageClassName: {{ .Values.pgBackRest.pvc.volume.storageClassName }}
      {{- if and .Values.restore .Values.restore.enabled }}
      restore:
        enabled: {{ .Values.restore.enabled }}
        repoName: repo1
        options:
          - --type=time
          - --target="{{ .Values.restore.target }}"
      {{- end }}
      # this stuff is for the "pgbackrest" container (the only non-init container) in the "postgres-crunchy-repo-host" pod
      repoHost:
        resources:
          requests:
            cpu: {{ .Values.pgBackRest.repoHost.requests.cpu }}
            memory: {{ .Values.pgBackRest.repoHost.requests.memory }}
      sidecars:
        # this stuff is for the "pgbackrest" container in the "postgres-crunchy-ha" set of pods
        pgbackrest:
          resources:
            requests:
              cpu: {{ .Values.pgBackRest.sidecars.requests.cpu }}
              memory: {{ .Values.pgBackRest.sidecars.requests.memory }}
        pgbackrestConfig:
          resources:
            requests:
              cpu: {{ .Values.pgBackRest.sidecars.requests.cpu }}
              memory: {{ .Values.pgBackRest.sidecars.requests.memory }}
      jobs:
        resources:
          requests:
            cpu: {{ .Values.pgBackRest.jobs.requests.cpu }}
            memory: {{ .Values.pgBackRest.jobs.requests.memory }}
  {{- end }}
  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - {{ .Values.patroni.postgresql.pg_hba}}
        parameters:
          shared_buffers: {{ .Values.patroni.postgresql.parameters.shared_buffers }}
          wal_buffers: {{ .Values.patroni.postgresql.parameters.wal_buffers }}
          min_wal_size: {{ .Values.patroni.postgresql.parameters.min_wal_size }}
          max_wal_size: {{ .Values.patroni.postgresql.parameters.max_wal_size }}
          max_slot_wal_keep_size:  {{ .Values.patroni.postgresql.parameters.max_slot_wal_keep_size }}
  {{- if and .Values.proxy .Values.proxy.enabled }}
  proxy:
    pgBouncer:
      config:
        global:
          client_tls_sslmode: disable
          pool_mode: transaction
      {{ if .Values.proxy.pgBouncer.image }}
      image: {{ .Values.proxy.pgBouncer.image }}
      {{ end }}
      replicas: {{ .Values.proxy.pgBouncer.replicas }}
      # these resources are for the "pgbouncer" container in the "postgres-crunchy-ha-pgbouncer" set of pods
      # there is a sidecar in these pods which are not mentioned here, but the requests/limits are teeny weeny by default so no worries there.
      resources:
        requests:
          cpu: {{ .Values.proxy.pgBouncer.requests.cpu }}
          memory: {{ .Values.proxy.pgBouncer.requests.memory }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster:
                      {{ .Values.instances.name }}
                    postgres-operator.crunchydata.com/role: pgbouncer
  {{- end }}
  {{- end }}
