SET search_path TO pay_transparency;

-- Add new codes for the hourly pay quartile calculations
insert into calculation_code 
  (calculation_code)
values 
  ('HOURLY_PAY_PERCENT_QUARTILE_1_M'),
  ('HOURLY_PAY_PERCENT_QUARTILE_1_W'),
  ('HOURLY_PAY_PERCENT_QUARTILE_1_X'),
  ('HOURLY_PAY_PERCENT_QUARTILE_1_U'),
  ('HOURLY_PAY_PERCENT_QUARTILE_2_M'),
  ('HOURLY_PAY_PERCENT_QUARTILE_2_W'),
  ('HOURLY_PAY_PERCENT_QUARTILE_2_X'),
  ('HOURLY_PAY_PERCENT_QUARTILE_2_U'),
  ('HOURLY_PAY_PERCENT_QUARTILE_3_M'),
  ('HOURLY_PAY_PERCENT_QUARTILE_3_W'),
  ('HOURLY_PAY_PERCENT_QUARTILE_3_X'),
  ('HOURLY_PAY_PERCENT_QUARTILE_3_U'),
  ('HOURLY_PAY_PERCENT_QUARTILE_4_M'),
  ('HOURLY_PAY_PERCENT_QUARTILE_4_W'),
  ('HOURLY_PAY_PERCENT_QUARTILE_4_X'),
  ('HOURLY_PAY_PERCENT_QUARTILE_4_U')
  ;

