# PR specific values for fin-pay-transparency.
# Only override specific values for pr pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  secrets:
    databaseName: ~
    databaseUser: ~
    databasePassword: ~
    adminKeycloakUrl: ~
    adminKeycloakClientId: ~
    adminKeycloakClientSecret: ~
    keycloakClientId: ~
    keycloakClientSecret: ~
    keycloakUrl: ~
    uiPrivateKey: ~
    uiPublicKey: ~
    bceidWsAuthPassword: ~
    bceidWsAuthUserName: ~
    bceidWsUrl: ~
    bceidWsOnlineServiceId: ~
    cssAppApiClientId: ~
    cssAppApiClientSecret: ~
    cssAppApiIntegrationId: ~
    cssAppApiEnvironment: "dev"
    externalConsumerApiKey: ~
    externalConsumerDeleteReportsApiKey: ~
    externalConsumerErrorReportsApiKey: ~
    chesClientID: ~
    chesTokenURL: ~
    chesClientSecret: ~
    chesAPIURL: ~
    chesEmailRecipients: ~
  domain: "apps.silver.devops.gov.bc.ca" # it is required, apps.silver.devops.gov.bc.ca for silver cluster
  autoscaling:
    enabled: false
  config:
    is_user_error_logging_enabled: "true"
  crunchyEnabled: false
  seedData: true
backend:
  deploymentStrategy: Recreate
  initResources:
    requests:
      cpu: 150m
      memory: 250Mi
  resources:
    requests:
      cpu: 50m
      memory: 250Mi
  storage:
    enabled: true
    size: 50Mi
    accessMode: ReadWriteMany
  pdb: false

frontend:
  deploymentStrategy: Recreate
  resources:
    requests:
      cpu: 15m
      memory: 50Mi
  env:
    logLevel: info
  pdb: false

admin-frontend:
  deploymentStrategy: Recreate
  resources:
    requests:
      cpu: 15m
      memory: 50Mi
  env:
    logLevel: info
  pdb: false

database:
  enabled: true
  deploymentStrategy: Recreate
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  imagePullSecrets: []
  autoscaling:
    enabled: false
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    requests:
      cpu: 30m
      memory: 100Mi
  persistence:
    enabled: true
    size: 80Mi
    accessMode: ReadWriteOnce
    storageClass: netapp-block-standard

crunchy:
  enabled: false

doc-gen-service:
  enabled: true
  deploymentStrategy: Recreate
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/bcgov/fin-pay-transparency/doc-gen-service
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ~
  containerPort: 3000
  environment: production
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  resources:
    requests:
      cpu: 50m
      memory: 150Mi

  podSecurityContext: {}
  securityContext: {}
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  pdb: false
