# PR specific values for fin-pay-transparency.
# Only override specific values for pr pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  secrets:
    databaseName: ~
    databaseUser: ~
    databasePassword: ~
    adminKeycloakUrl: ~
    adminKeycloakClientId: ~
    adminKeycloakClientSecret: ~
    keycloakClientId: ~
    keycloakClientSecret: ~
    keycloakUrl: ~
    uiPrivateKey: ~
    uiPublicKey: ~
    bceidWsAuthPassword: ~
    bceidWsAuthUserName: ~
    bceidWsUrl: ~
    bceidWsOnlineServiceId: ~
    cssAppApiClientId: ~
    cssAppApiClientSecret: ~
    cssAppApiIntegrationId: ~
    cssAppApiEnvironment: "dev"
    externalConsumerApiKey: ~
    externalConsumerDeleteReportsApiKey: ~
    externalConsumerErrorReportsApiKey: ~
    chesClientID: ~
    chesTokenURL: ~
    chesClientSecret: ~
    chesAPIURL: ~
    chesEmailRecipients: ~
  domain: "apps.silver.devops.gov.bc.ca" # it is required, apps.silver.devops.gov.bc.ca for silver cluster
  autoscaling:
    enabled: false
  config:
    is_user_error_logging_enabled: "true"
    delete_draft_report_cron_crontime: "40 10 * * *" # 10:30 AM PST/PDT
  crunchyEnabled: true
  seedData: false
backend:
  deploymentStrategy: Recreate
  initResources:
    requests:
      cpu: 150m
      memory: 250Mi
  resources:
    requests:
      cpu: 50m
      memory: 250Mi
  storage:
    enabled: true
    size: 50Mi
    accessMode: ReadWriteMany
  pdb: false

frontend:
  deploymentStrategy: Recreate
  resources:
    requests:
      cpu: 15m
      memory: 50Mi
  env:
    logLevel: info
  pdb: false

admin-frontend:
  deploymentStrategy: Recreate
  resources:
    requests:
      cpu: 15m
      memory: 50Mi
  env:
    logLevel: info
  pdb: false

database:
  enabled: false
crunchy:
  enabled: true
  postgresVersion: 17
  imagePullPolicy: IfNotPresent
  # enable below to start a new crunchy cluster after disaster from a backed-up location, crunchy will choose the best place to recover from.
  # follow https://access.crunchydata.com/documentation/postgres-operator/5.2.0/tutorial/disaster-recovery/
  # Clone From Backups Stored in S3 / GCS / Azure Blob Storage
  # TESTED SUCCESSFULLY
  clone:
    enabled: false
    path: ~ # provide the proper path to source the cluster. ex: /backups/cluster/version/1, if current new cluster being created, this should be current cluster version -1, ideally
  # enable this to go back to a specific timestamp in history in the current cluster.
  # follow https://access.crunchydata.com/documentation/postgres-operator/5.2.0/tutorial/disaster-recovery/
  # Perform an In-Place Point-in-time-Recovery (PITR)
  # need to fire this command `oc annotate postgrescluster pay-transparency-tools-crunchy --overwrite postgres-operator.crunchydata.com/pgbackrest-restore=repo1`
  # NOT TESTED SUCCESSFULLY
  restore:
    enabled: false
    target: ~ # 2024-03-24 17:16:00-07 this is the target timestamp to go back to in current cluster
  instances:
    name: db
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
    replicas: 1
    dataVolumeClaimSpec:
      storage: 1024Mi
      storageClassName: netapp-block-standard
    requests:
      cpu: 200m
      memory: 256Mi
    replicaCertCopy:
      requests:
        cpu: 20m
        memory: 32Mi

  patroni:
    postgresql:
      pg_hba: "host all all 0.0.0.0/0 md5"
      parameters:
        shared_buffers: 16MB # default is 128MB; a good tuned default for shared_buffers is 25% of the memory allocated to the pod
        wal_buffers: "64kB" # this can be set to -1 to automatically set as 1/32 of shared_buffers or 64kB, whichever is larger
        min_wal_size: 32MB
        max_wal_size: 128MB # default is 1GB
        max_slot_wal_keep_size: 128MB # default is -1, allowing unlimited wal growth when replicas fall behind

  proxy:
    enabled: true
    pgBouncer:
      image: # it's not necessary to specify an image as the images specified in the Crunchy Postgres Operator will be pulled by default
      replicas: 1
      requests:
        cpu: 20m
        memory: 32Mi

  # Postgres Cluster resource values:
  pgmonitor:
    enabled: true
    exporter:
      image: # it's not necessary to specify an image as the images specified in the Crunchy Postgres Operator will be pulled by default
      requests:
        cpu: 35m
        memory: 32Mi


doc-gen-service:
  enabled: true
  deploymentStrategy: Recreate
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/bcgov/fin-pay-transparency/doc-gen-service
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: ~
  containerPort: 3000
  environment: production
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  resources:
    requests:
      cpu: 50m
      memory: 150Mi

  podSecurityContext: {}
  securityContext: {}
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  pdb: false
