---
title: Pay Transparency System - Data Flow Diagram (L0)
---
flowchart LR    
    Org[Organization User] -->|"Employee pay data"| PT((Pay Transparency System))    
    AdminMgr[Admin Manager] -->|User invitation| PT
    AdminUser[Admin User] -->|Lock/unlock report| PT
    AdminUser -->|Announcement| PT
    KeyCloak -->|OIDC discovery document|PT 
    BCeIDBusiness[BusinessBCeID] -->|Company information|PT     
    PT --> |Email recipients,\ntitle, and body| EmailService[Common hosted\nemail service]        
    PT -->|Pay transparency report| Org
    Org -->|Login credentials|BCeIDBusiness
    KeyCloak --> |Backend tokens|PT
    PT --> |Frontend token|Org
    PT --> |Database backup|ObjectStore[Object Store]

