name: Approve Screenshots
on:
  workflow_dispatch:
    inputs:
      pull-request-number:
        description: 'Pull Request Number to update screenshots for'
        required: true
        type: number

jobs:
  update-screenshots:
    name: Update Screenshots
    uses: ./.github/workflows/.e2e.yml
    secrets: inherit
    with:
      frontend-url: https://pay-transparency-pr-${{ inputs.pull-request-number }}-frontend.apps.silver.devops.gov.bc.ca
      external-api-base-url: https://pay-transparency-pr-${{ inputs.pull-request-number }}-backend-external.apps.silver.devops.gov.bc.ca
      environment: dev
      timeout-minutes: 15
      update-screenshots: true
