name: Build And Deploy ClamAV To Tools
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 1 * *' # 1st day of every month at midnight PST

jobs:
  builds:
    name: Builds
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: [ clamav-service/clamav,
                   clamav-service/clamav-node
        ]
        include:
          - package: clamav-service/clamav
            build_file: ./clamav-service/clamav/Dockerfile
            triggers: ('clamav-service/')
            build_context: ./clamav-service/clamav
          - package: clamav-service/clamav-node
            build_file: ./clamav-service/Dockerfile
            triggers: ('clamav-service/')
            build_context: ./clamav-service

    steps:
      - uses: actions/checkout@v5
      - uses: bcgov/action-builder-ghcr@v4.1.0
        with:
          package: ${{ matrix.package }}
          tags: latest
          tag_fallback: latest
          build_context: ${{ matrix.build_context }}
          triggers: ${{ matrix.triggers }}
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    needs: builds
    environment: tools
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
        name: checkout
      - uses: bcgov/action-oc-runner@10033668ef4374d9bb78149faa73e4ccda0e93dd # v1.2.3
        name: Login to OpenShift
        with:
          oc_namespace: ${{ vars.oc_namespace }}
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.oc_token }} 
          # (NOTE: project command is a safeguard)
          commands: | 
             oc project ${{ vars.oc_namespace }}
      - name: Package ClamAV Helm Chart
        shell: bash
        run: |
          helm package -u  ./clamav-service/charts/clamav-service
      - name: Deploy ClamAV Helm Chart
        shell: bash
        run: |
          # CLAMAV_API_KEY is a secret stored in GitHub at repo level
          helm upgrade --debug --install --wait --atomic clamav-service  \
          --set-string global.secrets.apiKey=${{ secrets.CLAMAV_API_KEY }} \
          --timeout 9m ./clamav-service-1.0.0.tgz
          
