name: Build And Deploy to Sandbox in Dev namespace
on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "docker-compose.yml"
      - "renovate.json"
      - "COMPLIANCE.yaml"
      - ".gitignore"
      - ".vscode/**"
      - ".diagrams/**"
      - ".graphics/**"
      - "sysdig/**"
      - ".github/workflows/sysdig.yml"
      - "clamav-service/**"
    branches:
      - main

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  builds:
    if: (!github.event.pull_request.head.repo.fork)
    uses: ./.github/workflows/.build.yml

  deploys:
    name: Deploys
    needs: [builds]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      autoscaling: false
      target: pr-${{ github.event.number }}
      tag: pr-${{ github.event.number }}-${{ github.run_number }}
      values: "values-pr.yaml"
      frontend-url: https://pay-transparency-pr-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca
      admin-frontend-url: https://pay-transparency-pr-${{ github.event.number }}-admin-frontend.apps.silver.devops.gov.bc.ca
  test-integration:
    name: Integration
    needs: [builds, deploys]
    uses: ./.github/workflows/.integration.yml
    secrets: inherit
    with:
      backend-external-url: https://pay-transparency-pr-${{ github.event.number }}-backend-external.apps.silver.devops.gov.bc.ca/api
  test-e2e:
    name: E2E
    needs: [builds, deploys]
    uses: ./.github/workflows/.e2e.yml
    secrets: inherit
    with:
      frontend-url: https://pay-transparency-pr-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca
      external-api-base-url: https://pay-transparency-pr-${{ github.event.number }}-backend-external.apps.silver.devops.gov.bc.ca
  test-e2e-visual:
    name: E2E Visual Tests
    needs: [builds, deploys, test-e2e]
    uses: ./.github/workflows/.e2e-visual.yml
    secrets: inherit
    with:
      frontend-url: https://pay-transparency-pr-${{ github.event.number }}-frontend.apps.silver.devops.gov.bc.ca
      external-api-base-url: https://pay-transparency-pr-${{ github.event.number }}-backend-external.apps.silver.devops.gov.bc.ca
  test-e2e-admin:
    name: E2E-Admin
    needs: [builds, deploys, test-e2e, test-e2e-visual]
    uses: ./.github/workflows/.e2e-admin.yml
    secrets: inherit
    with:
      admin-frontend-url: https://pay-transparency-pr-${{ github.event.number }}-admin-frontend.apps.silver.devops.gov.bc.ca
