name: Merge to Main
env:
  deployment_name: pay-transparency
on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "docker-compose.yml"
      - "renovate.json"
      - "COMPLIANCE.yaml"
      - ".gitignore"
      - ".vscode/**"
      - ".diagrams/**"
      - ".graphics/**"
      - "sysdig/**"
      - ".github/workflows/sysdig.yml"
      - "clamav-service/**"
  workflow_dispatch:
    inputs:
      pr_no:
        description: "PR-numbered container set to deploy"
        type: number
        required: true

concurrency:
  group: merge-to-main
  cancel-in-progress: false # queue the workflows , if multiples are triggered.

jobs:
  vars:
    name: Set Variables
    outputs:
      pr: ${{ steps.pr.outputs.pr || inputs.pr_no}}
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps: # Get PR number for squash merges to main
      - name: PR Number
        if: (github.event_name != 'workflow_dispatch')
        id: pr
        uses: bcgov/action-get-pr@v0.1.1
  codeql:
    name: Semantic Code Analysis
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v6

      - name: Initialize
        uses: github/codeql-action/init@v4
        with:
          languages: javascript

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

  semantic-version: # Create a semantic version based on the commit messages and tag the commit.
    outputs:
      semanticVersion: ${{ steps.changelog.outputs.version }}
      tag: ${{ steps.changelog.outputs.tag }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v6
      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v6
        id: changelog
        continue-on-error: true
        with:
          preset: "conventionalcommits"
          github-token: ${{ github.token }}
          output-file: "CHANGELOG.md"
          skip-version-file: "true"
          skip-commit: "true"
          skip-on-empty: "false"
          git-push: "true"
  retag-images:
    needs: [vars, semantic-version]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package:
          [
            backend,
            database-migrations,
            admin-frontend,
            frontend,
            doc-gen-service,
            backend-external,
            maintenance,
          ]
    steps:
      - name: Tag Docker Images
        uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ needs.vars.outputs.pr }}
          tags: |
            ${{ needs.semantic-version.outputs.semanticVersion }}
            dev

  deploys:
    name: Deploys (dev)
    needs: [retag-images, semantic-version]
    uses: ./.github/workflows/.deploy.yml
    secrets: inherit
    with:
      target: dev
      tag: ${{ needs.semantic-version.outputs.semanticVersion }}
      frontend-url: https://dev.paytransparency.fin.gov.bc.ca
      admin-frontend-url: https://dev.ptrtadmin.fin.gov.bc.ca
      semver: ${{ needs.semantic-version.outputs.semanticVersion }}
      values: "values-dev.yaml"

  test-integration:
    name: Integration
    needs: [deploys]
    uses: ./.github/workflows/.integration.yml
    secrets: inherit
    with:
      backend-external-url: https://pay-transparency-dev-backend-external.apps.silver.devops.gov.bc.ca/api

  get-last-deployed-and-check-human:
    if: vars.PR_AUTO_APPROVAL_ENABLED == 'true'
    name: Get Last Deployed Version & Check Human Changes
    needs: [semantic-version, deploys]
    runs-on: ubuntu-24.04
    environment: prod
    permissions:
      actions: read
    outputs:
      latest_deployed_version: ${{ steps.get.outputs.latest_deployed_version }}
      human_changes_exist: ${{ steps.check.outputs.human_changes }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0
      
      - name: Ensure latest main
        run: |
          git fetch origin main
          git reset --hard origin/main
      
      - uses: bcgov/action-oc-runner@d2fc921aaa9d70684c186dbb7754e6985d44d86f # v1.4.1
        name: Login to OpenShift
        with:
          oc_namespace: db4642-prod
          oc_server: ${{ vars.oc_server }}
          oc_token: ${{ secrets.OC_TOKEN }} 
          commands: | 
             oc project db4642-prod

      - name: Fetch last deployed version for PROD environment
        id: get
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENV_NAME: prod          
        run: |         
          LATEST_DEPLOYED_VERSION=$(oc get deployments pay-transparency-${ENV_NAME}-backend -L app.kubernetes.io/image-version --no-headers | awk '{print $NF}')

          if [ -z "$LATEST_DEPLOYED_VERSION" ]; then
            echo "Missing latest deployment version"
            exit 1
          fi

          # Ensure 'v' is prepended if not already
          if [[ "$LATEST_DEPLOYED_VERSION" != v* ]]; then
            LATEST_DEPLOYED_VERSION="v$LATEST_DEPLOYED_VERSION"
          fi

          echo "Latest deployed Version: $LATEST_DEPLOYED_VERSION"
          echo "latest_deployed_version=$LATEST_DEPLOYED_VERSION" >> $GITHUB_OUTPUT

      - id: check
        run: |
          set -euo pipefail
      
          LAST_PROMOTED="${{ steps.get.outputs.latest_deployed_version }}"
          echo "Last promoted version: $LAST_PROMOTED"
      
          COMMITS=$(git log "${LAST_PROMOTED}..origin/main" \
            --pretty=format:'%H|%an|%ae')
      
          echo "Commits since last promotion:"
          echo "$COMMITS"
      
          HUMAN_CHANGES=false
      
          while IFS='|' read -r HASH AUTHOR EMAIL; do
            [ -z "$HASH" ] && continue
          
            if [[ "$EMAIL" =~ (renovate|dependabot) \
               || "$AUTHOR" =~ (renovate\[bot\]|dependabot\[bot\]) ]]; then
            echo "Bot commit: $AUTHOR <$EMAIL>"
            else
              HUMAN_CHANGES=true
              echo "Human commit detected: $AUTHOR <$EMAIL>"
              break
            fi
          done <<< "$COMMITS"
      
          echo "human_changes=$HUMAN_CHANGES" >> "$GITHUB_OUTPUT"

  trigger-test-deployment:
    name: Trigger Test Deployment
    if:  >
      ( github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]' ) &&
      ( needs.get-last-deployed-and-check-human.outputs.human_changes_exist == 'false' ) &&
      ( vars.PR_AUTO_APPROVAL_ENABLED == 'true' )
    needs: [deploys,test-integration,semantic-version,get-last-deployed-and-check-human]
    uses: ./.github/workflows/cd-to-test-on-workflow-dispatch.yml
    secrets: inherit
    with:
      tag: ${{ needs.semantic-version.outputs.semanticVersion }}
  
  trigger-prod-deployment:
    name: Trigger Prod Deployment
    if:  >
      ( github.actor == 'dependabot[bot]' || github.actor == 'renovate[bot]' ) &&
      ( needs.get-last-deployed-and-check-human.outputs.human_changes_exist == 'false' ) &&
      ( vars.PR_AUTO_APPROVAL_ENABLED == 'true' )
    needs: [deploys,test-integration,semantic-version,trigger-test-deployment,get-last-deployed-and-check-human]
    uses: ./.github/workflows/cd-to-prod-on-workflow-dispatch.yml
    secrets: inherit
    with:
      tag: ${{ needs.semantic-version.outputs.semanticVersion }}      
